// source: ondewo/t2s/custom_phonemizer.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.ondewo.t2s.CreateCustomPhonemizerRequest', null, global);
goog.exportSymbol('proto.ondewo.t2s.CustomPhonemizerProto', null, global);
goog.exportSymbol('proto.ondewo.t2s.ListCustomPhonemizerRequest', null, global);
goog.exportSymbol('proto.ondewo.t2s.ListCustomPhonemizerResponse', null, global);
goog.exportSymbol('proto.ondewo.t2s.Map', null, global);
goog.exportSymbol('proto.ondewo.t2s.PhonemizerId', null, global);
goog.exportSymbol('proto.ondewo.t2s.UpdateCustomPhonemizerRequest', null, global);
goog.exportSymbol('proto.ondewo.t2s.UpdateCustomPhonemizerRequest.UpdateMethod', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ondewo.t2s.PhonemizerId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ondewo.t2s.PhonemizerId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ondewo.t2s.PhonemizerId.displayName = 'proto.ondewo.t2s.PhonemizerId';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ondewo.t2s.CustomPhonemizerProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ondewo.t2s.CustomPhonemizerProto.repeatedFields_, null);
};
goog.inherits(proto.ondewo.t2s.CustomPhonemizerProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ondewo.t2s.CustomPhonemizerProto.displayName = 'proto.ondewo.t2s.CustomPhonemizerProto';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ondewo.t2s.Map = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ondewo.t2s.Map, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ondewo.t2s.Map.displayName = 'proto.ondewo.t2s.Map';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ondewo.t2s.ListCustomPhonemizerResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ondewo.t2s.ListCustomPhonemizerResponse.repeatedFields_, null);
};
goog.inherits(proto.ondewo.t2s.ListCustomPhonemizerResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ondewo.t2s.ListCustomPhonemizerResponse.displayName = 'proto.ondewo.t2s.ListCustomPhonemizerResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ondewo.t2s.ListCustomPhonemizerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ondewo.t2s.ListCustomPhonemizerRequest.repeatedFields_, null);
};
goog.inherits(proto.ondewo.t2s.ListCustomPhonemizerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ondewo.t2s.ListCustomPhonemizerRequest.displayName = 'proto.ondewo.t2s.ListCustomPhonemizerRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ondewo.t2s.UpdateCustomPhonemizerRequest.repeatedFields_, null);
};
goog.inherits(proto.ondewo.t2s.UpdateCustomPhonemizerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ondewo.t2s.UpdateCustomPhonemizerRequest.displayName = 'proto.ondewo.t2s.UpdateCustomPhonemizerRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ondewo.t2s.CreateCustomPhonemizerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ondewo.t2s.CreateCustomPhonemizerRequest.repeatedFields_, null);
};
goog.inherits(proto.ondewo.t2s.CreateCustomPhonemizerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ondewo.t2s.CreateCustomPhonemizerRequest.displayName = 'proto.ondewo.t2s.CreateCustomPhonemizerRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ondewo.t2s.PhonemizerId.prototype.toObject = function(opt_includeInstance) {
  return proto.ondewo.t2s.PhonemizerId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ondewo.t2s.PhonemizerId} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.t2s.PhonemizerId.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ondewo.t2s.PhonemizerId}
 */
proto.ondewo.t2s.PhonemizerId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ondewo.t2s.PhonemizerId;
  return proto.ondewo.t2s.PhonemizerId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ondewo.t2s.PhonemizerId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ondewo.t2s.PhonemizerId}
 */
proto.ondewo.t2s.PhonemizerId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ondewo.t2s.PhonemizerId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ondewo.t2s.PhonemizerId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ondewo.t2s.PhonemizerId} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.t2s.PhonemizerId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.ondewo.t2s.PhonemizerId.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ondewo.t2s.PhonemizerId} returns this
 */
proto.ondewo.t2s.PhonemizerId.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ondewo.t2s.CustomPhonemizerProto.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ondewo.t2s.CustomPhonemizerProto.prototype.toObject = function(opt_includeInstance) {
  return proto.ondewo.t2s.CustomPhonemizerProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ondewo.t2s.CustomPhonemizerProto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.t2s.CustomPhonemizerProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    mapsList: jspb.Message.toObjectList(msg.getMapsList(),
    proto.ondewo.t2s.Map.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ondewo.t2s.CustomPhonemizerProto}
 */
proto.ondewo.t2s.CustomPhonemizerProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ondewo.t2s.CustomPhonemizerProto;
  return proto.ondewo.t2s.CustomPhonemizerProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ondewo.t2s.CustomPhonemizerProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ondewo.t2s.CustomPhonemizerProto}
 */
proto.ondewo.t2s.CustomPhonemizerProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.ondewo.t2s.Map;
      reader.readMessage(value,proto.ondewo.t2s.Map.deserializeBinaryFromReader);
      msg.addMaps(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ondewo.t2s.CustomPhonemizerProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ondewo.t2s.CustomPhonemizerProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ondewo.t2s.CustomPhonemizerProto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.t2s.CustomPhonemizerProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMapsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.ondewo.t2s.Map.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.ondewo.t2s.CustomPhonemizerProto.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ondewo.t2s.CustomPhonemizerProto} returns this
 */
proto.ondewo.t2s.CustomPhonemizerProto.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Map maps = 2;
 * @return {!Array<!proto.ondewo.t2s.Map>}
 */
proto.ondewo.t2s.CustomPhonemizerProto.prototype.getMapsList = function() {
  return /** @type{!Array<!proto.ondewo.t2s.Map>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ondewo.t2s.Map, 2));
};


/**
 * @param {!Array<!proto.ondewo.t2s.Map>} value
 * @return {!proto.ondewo.t2s.CustomPhonemizerProto} returns this
*/
proto.ondewo.t2s.CustomPhonemizerProto.prototype.setMapsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.ondewo.t2s.Map=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ondewo.t2s.Map}
 */
proto.ondewo.t2s.CustomPhonemizerProto.prototype.addMaps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.ondewo.t2s.Map, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ondewo.t2s.CustomPhonemizerProto} returns this
 */
proto.ondewo.t2s.CustomPhonemizerProto.prototype.clearMapsList = function() {
  return this.setMapsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ondewo.t2s.Map.prototype.toObject = function(opt_includeInstance) {
  return proto.ondewo.t2s.Map.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ondewo.t2s.Map} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.t2s.Map.toObject = function(includeInstance, msg) {
  var f, obj = {
    word: jspb.Message.getFieldWithDefault(msg, 1, ""),
    phonemeGroups: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ondewo.t2s.Map}
 */
proto.ondewo.t2s.Map.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ondewo.t2s.Map;
  return proto.ondewo.t2s.Map.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ondewo.t2s.Map} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ondewo.t2s.Map}
 */
proto.ondewo.t2s.Map.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setWord(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhonemeGroups(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ondewo.t2s.Map.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ondewo.t2s.Map.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ondewo.t2s.Map} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.t2s.Map.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWord();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPhonemeGroups();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string word = 1;
 * @return {string}
 */
proto.ondewo.t2s.Map.prototype.getWord = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ondewo.t2s.Map} returns this
 */
proto.ondewo.t2s.Map.prototype.setWord = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string phoneme_groups = 2;
 * @return {string}
 */
proto.ondewo.t2s.Map.prototype.getPhonemeGroups = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ondewo.t2s.Map} returns this
 */
proto.ondewo.t2s.Map.prototype.setPhonemeGroups = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ondewo.t2s.ListCustomPhonemizerResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ondewo.t2s.ListCustomPhonemizerResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ondewo.t2s.ListCustomPhonemizerResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ondewo.t2s.ListCustomPhonemizerResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.t2s.ListCustomPhonemizerResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    phonemizersList: jspb.Message.toObjectList(msg.getPhonemizersList(),
    proto.ondewo.t2s.CustomPhonemizerProto.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ondewo.t2s.ListCustomPhonemizerResponse}
 */
proto.ondewo.t2s.ListCustomPhonemizerResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ondewo.t2s.ListCustomPhonemizerResponse;
  return proto.ondewo.t2s.ListCustomPhonemizerResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ondewo.t2s.ListCustomPhonemizerResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ondewo.t2s.ListCustomPhonemizerResponse}
 */
proto.ondewo.t2s.ListCustomPhonemizerResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ondewo.t2s.CustomPhonemizerProto;
      reader.readMessage(value,proto.ondewo.t2s.CustomPhonemizerProto.deserializeBinaryFromReader);
      msg.addPhonemizers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ondewo.t2s.ListCustomPhonemizerResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ondewo.t2s.ListCustomPhonemizerResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ondewo.t2s.ListCustomPhonemizerResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.t2s.ListCustomPhonemizerResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPhonemizersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.ondewo.t2s.CustomPhonemizerProto.serializeBinaryToWriter
    );
  }
};


/**
 * repeated CustomPhonemizerProto phonemizers = 1;
 * @return {!Array<!proto.ondewo.t2s.CustomPhonemizerProto>}
 */
proto.ondewo.t2s.ListCustomPhonemizerResponse.prototype.getPhonemizersList = function() {
  return /** @type{!Array<!proto.ondewo.t2s.CustomPhonemizerProto>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ondewo.t2s.CustomPhonemizerProto, 1));
};


/**
 * @param {!Array<!proto.ondewo.t2s.CustomPhonemizerProto>} value
 * @return {!proto.ondewo.t2s.ListCustomPhonemizerResponse} returns this
*/
proto.ondewo.t2s.ListCustomPhonemizerResponse.prototype.setPhonemizersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.ondewo.t2s.CustomPhonemizerProto=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ondewo.t2s.CustomPhonemizerProto}
 */
proto.ondewo.t2s.ListCustomPhonemizerResponse.prototype.addPhonemizers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.ondewo.t2s.CustomPhonemizerProto, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ondewo.t2s.ListCustomPhonemizerResponse} returns this
 */
proto.ondewo.t2s.ListCustomPhonemizerResponse.prototype.clearPhonemizersList = function() {
  return this.setPhonemizersList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ondewo.t2s.ListCustomPhonemizerRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ondewo.t2s.ListCustomPhonemizerRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ondewo.t2s.ListCustomPhonemizerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ondewo.t2s.ListCustomPhonemizerRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.t2s.ListCustomPhonemizerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    pipelineIdsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ondewo.t2s.ListCustomPhonemizerRequest}
 */
proto.ondewo.t2s.ListCustomPhonemizerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ondewo.t2s.ListCustomPhonemizerRequest;
  return proto.ondewo.t2s.ListCustomPhonemizerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ondewo.t2s.ListCustomPhonemizerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ondewo.t2s.ListCustomPhonemizerRequest}
 */
proto.ondewo.t2s.ListCustomPhonemizerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addPipelineIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ondewo.t2s.ListCustomPhonemizerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ondewo.t2s.ListCustomPhonemizerRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ondewo.t2s.ListCustomPhonemizerRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.t2s.ListCustomPhonemizerRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPipelineIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string pipeline_ids = 1;
 * @return {!Array<string>}
 */
proto.ondewo.t2s.ListCustomPhonemizerRequest.prototype.getPipelineIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.ondewo.t2s.ListCustomPhonemizerRequest} returns this
 */
proto.ondewo.t2s.ListCustomPhonemizerRequest.prototype.setPipelineIdsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.ondewo.t2s.ListCustomPhonemizerRequest} returns this
 */
proto.ondewo.t2s.ListCustomPhonemizerRequest.prototype.addPipelineIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ondewo.t2s.ListCustomPhonemizerRequest} returns this
 */
proto.ondewo.t2s.ListCustomPhonemizerRequest.prototype.clearPipelineIdsList = function() {
  return this.setPipelineIdsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ondewo.t2s.UpdateCustomPhonemizerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ondewo.t2s.UpdateCustomPhonemizerRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    updateMethod: jspb.Message.getFieldWithDefault(msg, 2, 0),
    mapsList: jspb.Message.toObjectList(msg.getMapsList(),
    proto.ondewo.t2s.Map.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ondewo.t2s.UpdateCustomPhonemizerRequest}
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ondewo.t2s.UpdateCustomPhonemizerRequest;
  return proto.ondewo.t2s.UpdateCustomPhonemizerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ondewo.t2s.UpdateCustomPhonemizerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ondewo.t2s.UpdateCustomPhonemizerRequest}
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!proto.ondewo.t2s.UpdateCustomPhonemizerRequest.UpdateMethod} */ (reader.readEnum());
      msg.setUpdateMethod(value);
      break;
    case 3:
      var value = new proto.ondewo.t2s.Map;
      reader.readMessage(value,proto.ondewo.t2s.Map.deserializeBinaryFromReader);
      msg.addMaps(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ondewo.t2s.UpdateCustomPhonemizerRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ondewo.t2s.UpdateCustomPhonemizerRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUpdateMethod();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getMapsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.ondewo.t2s.Map.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.UpdateMethod = {
  EXTEND_HARD: 0,
  EXTEND_SOFT: 1,
  REPLACE: 2
};

/**
 * optional string id = 1;
 * @return {string}
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ondewo.t2s.UpdateCustomPhonemizerRequest} returns this
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional UpdateMethod update_method = 2;
 * @return {!proto.ondewo.t2s.UpdateCustomPhonemizerRequest.UpdateMethod}
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.prototype.getUpdateMethod = function() {
  return /** @type {!proto.ondewo.t2s.UpdateCustomPhonemizerRequest.UpdateMethod} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.ondewo.t2s.UpdateCustomPhonemizerRequest.UpdateMethod} value
 * @return {!proto.ondewo.t2s.UpdateCustomPhonemizerRequest} returns this
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.prototype.setUpdateMethod = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * repeated Map maps = 3;
 * @return {!Array<!proto.ondewo.t2s.Map>}
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.prototype.getMapsList = function() {
  return /** @type{!Array<!proto.ondewo.t2s.Map>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ondewo.t2s.Map, 3));
};


/**
 * @param {!Array<!proto.ondewo.t2s.Map>} value
 * @return {!proto.ondewo.t2s.UpdateCustomPhonemizerRequest} returns this
*/
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.prototype.setMapsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.ondewo.t2s.Map=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ondewo.t2s.Map}
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.prototype.addMaps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.ondewo.t2s.Map, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ondewo.t2s.UpdateCustomPhonemizerRequest} returns this
 */
proto.ondewo.t2s.UpdateCustomPhonemizerRequest.prototype.clearMapsList = function() {
  return this.setMapsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ondewo.t2s.CreateCustomPhonemizerRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ondewo.t2s.CreateCustomPhonemizerRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ondewo.t2s.CreateCustomPhonemizerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ondewo.t2s.CreateCustomPhonemizerRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.t2s.CreateCustomPhonemizerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    prefix: jspb.Message.getFieldWithDefault(msg, 1, ""),
    mapsList: jspb.Message.toObjectList(msg.getMapsList(),
    proto.ondewo.t2s.Map.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ondewo.t2s.CreateCustomPhonemizerRequest}
 */
proto.ondewo.t2s.CreateCustomPhonemizerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ondewo.t2s.CreateCustomPhonemizerRequest;
  return proto.ondewo.t2s.CreateCustomPhonemizerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ondewo.t2s.CreateCustomPhonemizerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ondewo.t2s.CreateCustomPhonemizerRequest}
 */
proto.ondewo.t2s.CreateCustomPhonemizerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrefix(value);
      break;
    case 2:
      var value = new proto.ondewo.t2s.Map;
      reader.readMessage(value,proto.ondewo.t2s.Map.deserializeBinaryFromReader);
      msg.addMaps(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ondewo.t2s.CreateCustomPhonemizerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ondewo.t2s.CreateCustomPhonemizerRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ondewo.t2s.CreateCustomPhonemizerRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.t2s.CreateCustomPhonemizerRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPrefix();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMapsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.ondewo.t2s.Map.serializeBinaryToWriter
    );
  }
};


/**
 * optional string prefix = 1;
 * @return {string}
 */
proto.ondewo.t2s.CreateCustomPhonemizerRequest.prototype.getPrefix = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ondewo.t2s.CreateCustomPhonemizerRequest} returns this
 */
proto.ondewo.t2s.CreateCustomPhonemizerRequest.prototype.setPrefix = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Map maps = 2;
 * @return {!Array<!proto.ondewo.t2s.Map>}
 */
proto.ondewo.t2s.CreateCustomPhonemizerRequest.prototype.getMapsList = function() {
  return /** @type{!Array<!proto.ondewo.t2s.Map>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ondewo.t2s.Map, 2));
};


/**
 * @param {!Array<!proto.ondewo.t2s.Map>} value
 * @return {!proto.ondewo.t2s.CreateCustomPhonemizerRequest} returns this
*/
proto.ondewo.t2s.CreateCustomPhonemizerRequest.prototype.setMapsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.ondewo.t2s.Map=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ondewo.t2s.Map}
 */
proto.ondewo.t2s.CreateCustomPhonemizerRequest.prototype.addMaps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.ondewo.t2s.Map, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ondewo.t2s.CreateCustomPhonemizerRequest} returns this
 */
proto.ondewo.t2s.CreateCustomPhonemizerRequest.prototype.clearMapsList = function() {
  return this.setMapsList([]);
};


goog.object.extend(exports, proto.ondewo.t2s);
